apiVersion: v1
kind: Service
metadata:
  name: java-tomcat-app-service
spec:
  selector:
    app: java-tomcat-app
  ports:
    - protocol: TCP
      port: 80  # External port to access the service
      targetPort: 8100  # The port your app is running on inside the container
      nodePort:   # The external port exposed on each node
  type: NodePort  # Exposes the service via a NodePort
